In [5]:
import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l

In [6]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [7]:
layer = CenteredLayer()
layer(torch.tensor([1.0, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [8]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())

In [9]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(6.0536e-09, grad_fn=<MeanBackward0>)

In [10]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [11]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-1.2819, -0.7577, -0.8004],
        [-1.3787, -0.9266, -0.7929],
        [ 1.3742,  0.5867, -1.4175],
        [-1.9100, -0.1239, -0.7619],
        [-0.3477, -0.9966,  0.6216]], requires_grad=True)

In [12]:
linear(torch.rand(2, 5))

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.4503]])

In [13]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[6.3510],
        [4.7023]])